### ISSUE TITLE
Website: baidu.com

### ISSUE THREAD

**Issue by SettingDust** [DrKain/tidy-url#16]
**Website you would like added. Include multiple URLs if needed**

```js
  [
    'https://www.baidu.com/s?wd=%E6%96%87%E7%AB%A0%E8%A7%A3%E6%9E%90&rsv_spt=1&rsv_iqid=0xa2c2d4130003bffe&issp=1&f=8&rsv_bp=1&rsv_idx=2&ie=utf-8&tn=baiduhome_pg&rsv_enter=1&rsv_dl=tb&rsv_sug3=15&rsv_sug1=4&rsv_sug7=100&rsv_sug2=0&rsv_btype=i&inputT=3932&rsv_sug4=3932',
    'https://www.baidu.com/s?wd=%E6%96%87%E7%AB%A0%E8%A7%A3%E6%9E%90'
  ],
  [
    'https://www.baidu.com/s?wd=%E5%8F%91%E7%8E%B0%E9%9B%AA%E7%B3%95%E4%B8%8D%E6%A0%87%E4%BB%B7%E5%8F%AF%E7%AB%8B%E5%8D%B3%E6%8A%95%E8%AF%89&tn=baidutop10&rsv_idx=2&usm=2&ie=utf-8&rsv_pq=e0f4b7c10001f0bc&oq=%E5%A4%A7%E8%BF%9E%E4%B8%83%E5%A4%A9%E8%BF%9E%E9%94%81%E9%85%92%E5%BA%97%E8%A2%AB%E7%BD%A9%E7%8E%B0%E5%A4%A7%E7%89%87%E8%A1%80%E6%B8%8D&rsv_t=8e49rSMC2foDX76b7O7WNxzDrApXbODpIByXNOOd7HP1mvXBGgeUZF%2BVaN8B%2BFRC8A&rqid=e0f4b7c10001f0bc&rsf=c848d1aefa867f1211060bf1089d9bf1_16_30_23&rsv_dl=0_right_fyb_pchot_20811&sa=0_right_fyb_pchot_20811',
    'https://www.baidu.com/s?wd=%E5%8F%91%E7%8E%B0%E9%9B%AA%E7%B3%95%E4%B8%8D%E6%A0%87%E4%BB%B7%E5%8F%AF%E7%AB%8B%E5%8D%B3%E6%8A%95%E8%AF%89'
  ]
```
**Bad parameters. Leave blank if you don't know.**

- rsv_*
- rsf
- ...

**Comment by DrKain** [comment]
Added in https://github.com/DrKain/tidy-url/commit/82b6d3b66386beb56409a16db4e57f3901ee2af1 and https://github.com/DrKain/tidy-url/commit/25d5c28ad0df7e6ef4bb3005aec4c090b164b185 v1.4.4

I've tested best I can using information from [here](https://chineseseoshifu.com/blog/complete-list-of-baidu-search-url-parameters.html) + trial and error, as the linked page is slightly outdated.  

I do not speak Chinese, so if any parameters are important to page functionality please let me know so I can correct the rule.  

Some parameters were excluded because they may be useful (like `ie`) or I was unable to verify the use. EG: `inputT`, `f` and `issp`.
